title: Edion
logo: /assets/logo.png
description: The organization behind the autonomous interplanetary educational system of the same name.
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
