title: Edion
logo: /assets/logo.png
description: Educational tools designed to empower teachers and students.
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
